### ISSUE TITLE
My android device is not running this code

### ISSUE THREAD

**Issue by thanhansoft** [samarthagarwal/FutureBuildInFlutter#1]
Hi guy,

On android studio runs very well. I built the .apk file as instructed at https://flutter.dev/docs/deployment/android#build-an-apk. I only have loading on my device https://imgur.com/Fx9eABI

This is my json file http://www.json-generator.com/api/json/get/bUkDQsuXKG?indent=2

This is my code: [main.dart.txt](https://github.com/samarthagarwal/FutureBuildInFlutter/files/3995655/main.dart.txt)

Please help me

**Comment by samarthagarwal** [comment]
Do you get the data logged if you print `jsonData`?

**Comment by thanhansoft** [comment]
> Do you get the data logged if you print `jsonData`?

Thank for reply. My problem has been solved. So my phone cannot access the Internet. I need add 2 line in file: AndroidManifest.xml
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
